services:
  postfix:
    container_name: postfix
    image: boky/postfix:latest
    ports:
      - 25:25/tcp
    env_file:
      - ./postfix/postfix.env
    volumes:
      - /mnt/app/db/postfix/queue:/var/spool/postfix
      - ./postfix/sender_canonical_maps:/etc/postfix/sender_canonical_maps:ro
    restart: unless-stopped

  checkrr:
    container_name: checkrr
    image: aetaric/checkrr:latest
    ports:
      - 8585:8585/tcp
    volumes:
      - /mnt/app/db/checkrr/checkrr.yaml:/etc/checkrr.yaml
      - /mnt/app/db/checkrr:/config
      - /mnt/data/media:/media
    restart: unless-stopped

  rclone:
    image: rclone/rclone
    container_name: rclone
    ports:
      - 5572:5572/tcp
    volumes:
      - /mnt/app/db/rclone:/config/rclone
      - /mnt/app/db/rclone:/logs
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /dev/fuse:/dev/fuse
      - /mnt/data:/data
      - /mnt/app:/opt
      - /tmp/rclone:/htmp
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    command: rcd -v --rc-web-gui --rc-web-gui-no-open-browser --rc-addr :5572 --rc-user rclone --rc-pass rclone --transfers=3 --copy-links

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/linux
      - PGID=999
    volumes:
      - /mnt/app/db/crowdsec/config:/etc/crowdsec
      - /mnt/app/db/crowdsec/data:/var/lib/crowdsec/data
      - /mnt/app/db/traefik/logs:/var/log/traefik:ro
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.d/traefik.yaml:ro
    ports:
      - "1.1.1.1:8180:8080"
    restart: unless-stopped
    networks:
      - default
      - nas_default

  crowdsec-firewall-bouncer:
    image: ghcr.io/shgew/cs-firewall-bouncer-docker:latest
    container_name: crowdsec-firewall-bouncer
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./crowdsec/crowdsec-firewall-bouncer.yaml:/config/crowdsec-firewall-bouncer.yaml:ro
    restart: unless-stopped
    depends_on:
      - crowdsec

  drydock:
    container_name: drydock
    image: codeswhat/drydock
    depends_on:
      socket-proxy:
        condition: service_healthy
    environment:
      - DD_WATCHER_LOCAL_HOST=socket-proxy
      - DD_WATCHER_LOCAL_PORT=2375
      - DD_ANONYMOUS_AUTH_CONFIRM=true
      - DD_SECURITY_SCANNER=trivy
    ports:
      - 3004:3000

  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - EVENTS=1
      - SERVICES=1
    healthcheck:
      test: wget --spider http://localhost:2375/version || exit 1
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped

networks:
  nas_default:
    external: true
