services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/app/db/gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - SERVER_REGIONS=SOME_REGION
      - OPENVPN_USER=user
      - OPENVPN_PASSWORD=pass
      - FIREWALL_OUTBOUND_SUBNETS=1.1.1.1/1
      - HTTP_CONTROL_SERVER_ADDRESS=:8011
    ports:
      - 8888:8888/tcp # HTTP
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8191:8191/tcp # flaresolverr
      - 9696:9696/tcp # prowlarr
      - 7474:7474/tcp # autobrr
      - 9000:9000/tcp # thelounge
      - 8011:8011 #control server
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/prowlarr:/config
    network_mode: "service:gluetun"
    restart: unless-stopped
    depends_on:
      - gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=999
      - PGID=999
    volumes:
      - /mnt/app/db/sonarr/config:/config
      - /mnt/app/db/sonarr/custom-cont-init.d:/custom-cont-init.d
      - /mnt/app/db/sonarr/custom-services.d:/custom-services.d
      - /mnt/data:/data
      - /mnt/app/download:/download
    ports:
      - 8989:8989
    restart: unless-stopped

  sonarr4k:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr4k
    environment:
      - PUID=999
      - PGID=999
    volumes:
      - /mnt/app/db/sonarr4k/config:/config
      - /mnt/data:/data
      - /mnt/app/download:/download
    ports:
      - 9090:9090
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:develop
    container_name: radarr
    environment:
      - PUID=999
      - PGID=999
    volumes:
      - /mnt/app/db/radarr/config:/config
      - /mnt/app/db/radarr/custom-cont-init.d:/custom-cont-init.d
      - /mnt/app/db/radarr/custom-services.d:/custom-services.d
      - /mnt/data:/data
      - /mnt/app/download:/download
    ports:
      - 7878:7878
    restart: unless-stopped

  radarr4k:
    image: lscr.io/linuxserver/radarr:develop
    container_name: radarr4k
    environment:
      - PUID=999
      - PGID=999
    volumes:
      - /mnt/app/db/radarr4k/config:/config
      - /mnt/data:/data
      - /mnt/app/download:/download
    ports:
      - 7979:7979
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:develop
    container_name: lidarr
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/lidarr/config:/config
      - /mnt/app/db/lidarr/custom-services.d:/custom-services.d
      - /mnt/app/db/lidarr/custom-cont-init.d:/custom-cont-init.d
      - /mnt/data:/data
      - /mnt/app/download:/download
      - /mnt/data/media/music-videos:/music-videos
      - /mnt/data/media/music-lidarr-extended:/downloads-lidarr-extended
    ports:
      - 8686:8686
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/bazarr/config:/config
      - /mnt/app/db/bazarr/subcleaner:/subcleaner
      - /mnt/data:/data
    ports:
      - 6767:6767
    restart: unless-stopped

  bazarr4k:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr4k
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/bazarr4k/config:/config
      - /mnt/app/db/bazarr4k/subcleaner:/subcleaner
      - /mnt/data:/data
    ports:
      - 6868:6868
    restart: unless-stopped

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: whisper
    environment:
      - ASR_MODEL=distil-large-v3
      - ASR_ENGINE=whisperx
      - ASR_DEVICE=cpu
      - ASR_QUANTIZATION=float32
      - HF_TOKEN=hf_token_here
    ports:
      - 9001:9000
    restart: unless-stopped

  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    user: 999:999
    environment:
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/autobrr/config:/config
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  lounge:
    container_name: lounge
    image: ghcr.io/thelounge/thelounge:latest
    restart: unless-stopped
    volumes:
      - /mnt/app/db/lounge:/var/opt/thelounge
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/tautulli/data:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  kometa:
    image: kometateam/kometa:latest
    container_name: kometa
    environment:
      - KOMETA_CONFIG=/config/config.yml
      - KOMETA_TIMES=10:00
    volumes:
      - /mnt/app/db/kometa:/config
      - ./kometa/r:/r
      - ./kometa/rc:/rc
      - ./kometa/rc:/rf
      - ./kometa/ov:/ov
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    environment:
      - TZ=Some/Region
    user: 999:999
    volumes:
      - /mnt/app/db/recyclarr:/config

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
    network_mode: "service:gluetun"
    restart: unless-stopped
    depends_on:
      - gluetun

  gluetun-qbt:
    image: qmcgaw/gluetun:latest
    container_name: gluetun-qbt
    environment:
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - VPN_SERVICE_PROVIDER=private internet access
      - SERVER_REGIONS=SOME_REGION
      - OPENVPN_USER=user
      - OPENVPN_PASSWORD=pass
      - FIREWALL_OUTBOUND_SUBNETS=1.1.1.1/1
      - HTTP_CONTROL_SERVER_ADDRESS=:8005
      - HEALTH_VPN_DURATION_INITIAL=999h
      - HEALTH_SUCCESS_WAIT_DURATION=30s
      - DOT=off
      - BLOCK_MALICIOUS=off
    volumes:
      - /mnt/app/db/gluetun-qbt:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881 #BT
      - 6881:6881/udp #qBT
      - 8081:8081 #qBT
      - 8005:8005 #control server
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
      - WEBUI_PORT=8081
      - DOCKER_MODS=ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main
      - GSP_QBT_ADDR=http://localhost:8081
      - GSP_GTN_ADDR=http://localhost:8005
      - GSP_GTN_API_KEY=keyy
    volumes:
      - /mnt/app/db/qbittorrent:/config
      - /mnt/transcode/download:/download
    network_mode: "service:gluetun-qbt"
    depends_on:
      - gluetun-qbt
    restart: unless-stopped

  qui:
    image: ghcr.io/autobrr/qui:latest
    container_name: qui
    volumes:
      - /mnt/app/db/qui:/config
    ports:
      - 7476:7476
    depends_on:
      - qbittorrent
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/sabnzbd:/config
      - /mnt/app/download:/download
    ports:
      - 8085:8085
    restart: unless-stopped

  unpackerr:
    image: golift/unpackerr:latest
    container_name: unpackerr
    user: 999:999
    environment:
      - TZ=Some/Region
      - UN_LOG_FILE=/logs/unpackerr.log
      - UN_LOG_QUEUES=20m
      - UN_SONARR_0_URL=http://server.mylocal:8989
      - UN_SONARR_0_API_KEY=keyy
      - UN_SONARR_0_PROTOCOLS=torrent,usenet
      - UN_SONARR_1_URL=http://server.mylocal:9090
      - UN_SONARR_1_API_KEY=keyy
      - UN_SONARR_1_PROTOCOLS=torrent,usenet
      - UN_RADARR_0_URL=http://server.mylocal:7878
      - UN_RADARR_0_API_KEY=keyy
      - UN_RADARR_0_PROTOCOLS=torrent,usenet
      - UN_RADARR_1_URL=http://server.mylocal:7979
      - UN_RADARR_1_API_KEY=keyy
      - UN_RADARR_1_PROTOCOLS=torrent,usenet
      - UN_LIDARR_0_URL=http://server.mylocal:8686
      - UN_LIDARR_0_API_KEY=keyy
      - UN_LIDARR_0_PROTOCOLS=torrent,usenet
    volumes:
      - /mnt/app/download:/download
      - /mnt/app/db/unpackerr/logs:/logs
    restart: unless-stopped

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeName=server
    volumes:
      - /mnt/app/db/tdarr/server:/app/server
      - /mnt/app/db/tdarr/configs:/app/configs
      - /mnt/app/db/tdarr/logs:/app/logs
      - /mnt/app/db/tdarr/transcode:/temp
      - /mnt/data/media:/media
      - /mnt/data/user/Download:/download
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/dri:/dev/dri

  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:latest
    container_name: maintainerr
    user: 999:999
    volumes:
      - /mnt/app/db/maintainerr:/opt/data
      - /mnt/data/media:/media
    environment:
      - TZ=Some/Region
    ports:
      - 6246:6246
    restart: unless-stopped

  organizr:
    container_name: organizr
    image: organizr/organizr:latest
    ports:
      - 9393:80
    volumes:
      - /mnt/app/db/organizr:/config
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=server.mylocal:3001
    ports:
      - 3001:3000
    volumes:
      - /mnt/app/db/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
      - /mnt/app/download:/download:ro
      - /mnt/data/media:/data/media:ro
      - /mnt/transcode:/transcode:ro
