#!/bin/bash

if [ $HOSTNAME = "upgrade" ]; then
    docker compose -f "/mnt/home/user/compose/test/docker-compose.yml" up -d
    exit 
fi

docker compose -f "/mnt/app/home/user/compose/sys/docker-compose.yml" up -d
docker compose -f "/mnt/app/home/user/compose/monproxy/docker-compose.yml" up -d
docker compose -f "/mnt/app/home/user/compose/nas/docker-compose.yml" up -d
docker compose -f "/mnt/app/home/user/compose/media/docker-compose.yml" up -d
