---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Plex:
    - Plex:
        icon: plex.png
        href: https://plex.yourdomain.com
        server: server-docker
        container: plex
        widget:
            type: plex
            url: https://plex.yourdomain.com
            key: keyyyy

    - Tautulli:
        icon: tautulli.png
        href: http://server.mylocal:8181
        server: server-docker
        container: tautulli
        widget:
            type: tautulli
            url: http://server.mylocal:8181
            key: keyyyy

    - TrueNAS:
        icon: truenas.png
        href: http://server.mylocal:81
        widget:
            type: truenas
            url: http://server.mylocal:81
            key: keyyyyyy
            fields: ["load", "uptime", "alerts"]

    - Zabbix:
        icon: zabbix.png
        widget:
            type: zabbix
            url: https://zabbix.yourdomain.com
            key: keyyyy
            fields: ["warning", "average", "high", "disaster"]

- Media Management:
    - Radarr:
        icon: radarr.png
        href: http://server.mylocal:7878
        server: server-docker
        container: radarr
        widget:
            type: radarr
            url: http://server.mylocal:7878
            key: keyyyy
            fields: ["queued", "wanted"]

    - Radarr (4k):
        icon: radarr.png
        href: http://server.mylocal:7979
        server: server-docker
        container: radarr4k
        widget:
            type: radarr
            url: http://server.mylocal:7979
            key: keyyyy
            fields: ["queued", "wanted"]

    - Sonarr:
        icon: sonarr.png
        href: http://server.mylocal:8989
        server: server-docker
        container: sonarr
        widget:
            type: sonarr
            url: http://server.mylocal:8989
            key: keyyyy
            fields: ["queued", "wanted"]

    - Sonarr (4k):
        icon: sonarr.png
        href: http://server.mylocal:9090
        server: server-docker
        container: sonarr4k
        widget:
            type: sonarr
            url: http://server.mylocal:9090
            key: keyyyy
            fields: ["queued", "wanted"]

    - Lidarr:
        icon: lidarr.png
        href: http://server.mylocal:8686
        server: server-docker
        container: lidarr
        widget:
            type: lidarr
            url: http://server.mylocal:8686
            key: keyyyy
            fields: ["queued"]

    - Bazarr:
        icon: bazarr.png
        href: http://server.mylocal:6767
        server: server-docker
        container: bazarr
        widget:
            type: bazarr
            url: http://server.mylocal:6767
            key: keyyyy
            fields: ["missingEpisodes", "missingMovies"]

    - Bazarr (4k):
        icon: bazarr.png
        href: http://server.mylocal:6868
        server: server-docker
        container: bazarr4k
        widget:
            type: bazarr
            url: http://server.mylocal:6868
            key: keyyyy
            fields: ["missingEpisodes", "missingMovies"]

    - Audiobookshelf:
        icon: audiobookshelf
        href: http://server.mylocal:13378
        server: server-docker
        container: audiobookshelf
        widget:
            type: audiobookshelf
            url: http://server.mylocal:13378
            key: keyyyy
            fields: ["books", "booksDuration"]

- Requests & Downloads:
    - Seerr:
        icon: overseerr.png
        href: https://requests.yourdomain.com
        server: server-docker
        container: seerr
        widget:
            type: overseerr
            url: https://requests.yourdomain.com
            key: keyyyy
            fields: ["approved", "processing"]

    - sabnzbd:
        icon: sabnzbd
        href: http://server.mylocal:8085/sabnzbd
        server: server-docker
        container: sabnzbd
        widget:
            type: sabnzbd
            url: http://server.mylocal:8085/sabnzbd
            key: keyyyy
            fields: ["rate", "queue", "timeleft"]

    - qBittorrent:
        icon: qbittorrent
        href: http://server.mylocal:8081
        server: server-docker
        container: qbittorrent
        widget:
            type: qbittorrent
            url: http://server.mylocal:8081
            user: user
            password: pass
            fields: ["leech", "download", "seed", "upload"]

    - Autobrr:
        icon: autobrr.png
        href: http://server.mylocal:7474
        server: server-docker
        container: autobrr
        widget:
            type: autobrr
            url: http://server.mylocal:7474
            key: keyyyy
            fields: ["approvedPushes", "rejectedPushes"]

    - Tdarr:
        icon: tdarr.png
        href: http://server.mylocal:8265
        server: server-docker
        container: tdarr
        widget:
            type: tdarr
            url: http://server.mylocal:8265
            fields: ["queue", "errored"]

- Networking:
    - gluetun:
        icon: gluetun
        server: server-docker
        container: gluetun
        widget:
            type: gluetun
            url: http://server.mylocal:8011
            key: keyyyy
            fields: ["public_ip", "region", "country"]

    - gluetun (qbt):
        icon: gluetun
        server: server-docker
        container: gluetun-qbt
        widget:
            type: gluetun
            url: http://server.mylocal:8005
            key: keyyyy
            fields: ["public_ip", "region", "country"]

    - Traefik:
        icon: traefik.png
        href: http://server.mylocal:8282
        server: server-docker
        container: traefik
        widget:
            type: traefik
            url: http://server.mylocal:8282
            fields: ["routers", "services", "middleware"]
